### ISSUE TITLE
Change layout to src/

### ISSUE THREAD

**Issue by EnricoGavagnin** [nestauk/nesta_ds_utils#28]
Change package structure to:

| pyproject.toml
| README.md
| setup.py
| setup.cfg
| -- src
| &nbsp;   &nbsp;   | --  nesta_ds_utils
| &nbsp;   &nbsp;   |  &nbsp;   &nbsp;    | &nbsp;     modules.py
| &nbsp;   &nbsp;   |  &nbsp;   &nbsp;    | &nbsp;    __init__.py

| -- tests
| &nbsp;   &nbsp;   |  &nbsp;  test_module.py

**Comment by emily-bicks** [comment]
Possible layout within nesta_ds_utils:
```
nesta_ds_utils
>loading_saving
>> file_ops.py
>> s3_helpers.py

>cleaning
>>datetime_ops.py

>analysis
>>network_analysis
>>>generating_networks.py
>>>analysing_networks.py

>visualisation
>>altair_helpers
>>>nesta_theme.py
>>>saving.py
```
