### ISSUE TITLE
Documentation Styling

### ISSUE THREAD

**Issue by emily-bicks** [nestauk/nesta_ds_utils#35]
1. Convert to more visually appealing colors
2. Fix issue with sidebar (had to make it wide to fit long function definitions, but then doesn't resize)
3. Potentially change theme

**Comment by georgerichardson** [comment]
I don't think the averta font is supported on all browsers. Prob worth forgoing the full Nesta style in favour of something that works across platforms.

<img width="390" alt="image" src="https://user-images.githubusercontent.com/6348211/195887745-928e57cc-353b-4de3-afbd-e7e3db28096c.png">
