### ISSUE TITLE
[Bug]: Altair has been updated to v5, which means we can't import from v4.

### ISSUE THREAD

**Issue by VolcanoBlue13** [nestauk/nesta_ds_utils#87]
### Describe the Bug

Altair has been updated to v5, which means this import (`from altair.vegalite.v4.api import Chart`) in https://github.com/nestauk/nesta_ds_utils/blob/dev/nesta_ds_utils/viz/altair/saving.py, no longer works, if using the latest version of altair.

### Instructions to Reproduce the Bug

I've installed the latest altair (v5) in repo, which means when I ran `from nesta_ds_utils.viz.altair import formatting, saving`, it couldn't run the line `from altair.vegalite.v4.api import Chart`.

**Comment by j-gillam** [comment]
Just had a look at this. You can fix `from altair.vegalite.v4.api import Chart` by replacing all instances with alt.Chart. 

But there is still a bug when trying to use V5. It looks like it is on altair-viewers end. They have put a fix in github but not updated the package on PyPI. So a temporary get around would be downloading the package from there instead? Using `pip install git+https://github.com/altair-viz/altair_viewer` until they update the package. Any suggestions @sqr00t ?

**Comment by sqr00t** [comment]
We've pinned the requirement for altair to be 4.2.0, so there should likely be a conflict message when setting up the repo with `make install`.

@VolcanoBlue13 could you please also let me know the below points:

- Which repo you've tried to add Altair v5?
- Is there specific features/ functions that you'd need only available in v5? In this case, this would a feature request to support Altair v5.

Meanwhile, possible fixes:

1. Install altair<5 `pip install altair<5`, pinning in your requirements accordingly
2. Add a `try-except` to try importing v4, and try importing v5 instead if it fails
3. Change `from altair.vegalite.v4.api import Chart` to `from altair.vegalite import Chart` since:
    - [.vegalite imports everything in .v5 with __init__.py](https://github.com/altair-viz/altair/blob/main/altair/vegalite/__init__.py)
    - [.v5 imports Chart class from api.py with __init__.py](https://github.com/altair-viz/altair/blob/main/altair/vegalite/v5/__init__.py)

**Comment by VolcanoBlue13** [comment]
@sqr00t I'm going to be honest, I can't remember why I wanted altair v5 over v4... I think it was something to do with graph plotting, I could only make a certain graph in v5. I suggest I just continue with v4 until I come up against the same problem and then I'll make a note here! I would say that reading the release notes for v5, the thing that was of particular interest to me is the following addition:

- Responsive width support using width="container" when saving charts to html or displaying them with the default html renderer (#2867).

We had the issue when putting altair charts into Shorthand reports that they wouldn't respond to the different devices, so if viewing on a phone, you had to scroll sideways to view the whole chart, so I can see this feature being important for sharing our altair charts in Shorthand.

**Comment by sqr00t** [comment]
In this case I'd be inclined to follow the 3rd option:

 PR #90  opened addressing this with the following changes:

1. Change `from altair.vegalite.v4.api import Chart` to `from altair.vegalite import Chart`, you can then test changes with `pip install git+https://github.com/nestauk/nesta_ds_utils.git@87_support_altair_v5`
    - I've tested this and then `pip install 'altair>=5.0'` and didn't run into any issues
2. Check if there's conflicts between the version 4.2.0 pin in setup.cfg, with defining Altair version 5 in a project repo, and running `make install` or `make conda-update`
3. Change the version pin to accommodate >= 4.2.0 (or remove it), if there is conflicts

**Comment by sqr00t** [comment]
Please open a new issue if you face bugs related to `altair 5.0`. It appears full backward compatibility is now broken with pinned `altair==4.2.0`. In the face of several sweeping upstream API updates in the `[viz]` extra, I am moving in favour to set pins to >=(last known working version), and adapting requirements to latest. More details: #92
